# Site settings
title: Kite Development Guide
email: cdk-dev@cloudera.org
description: "An open source data API for Hadoop."
baseurl: "/docs/current"
url: "http://kitesdk.org"

license_url: "http://www.apache.org/licenses/LICENSE-2.0.html"
github_url: "https://github.com/kite-sdk/kite"
issue_tracker_url: "https://issues.cloudera.org/browse/CDK"
mailing_list_url: "https://groups.google.com/a/cloudera.org/forum/#!forum/cdk-dev"
contributing_url: "https://github.com/kite-sdk/kite/wiki/How-to-contribute"

dataset-command: "kite-dataset"

# Build settings
include: ["./samples/"]
markdown: kramdown

kramdown:
  input: GFM
  coderay_line_numbers: table
  

